#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         Quick Testing Commands for Your MCP Server            ║"
echo "╔════════════════════════════════════════════════════════════════╗"
echo ""

echo "📍 Project Location: $(pwd)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "1️⃣  CHECK IF SERVER IS RUNNING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo "  curl http://localhost:8000/"
echo ""
echo "Try it now:"
curl -s http://localhost:8000/ 2>/dev/null && echo "" || echo "❌ Server not running! Start with: uvicorn main:app --reload"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "2️⃣  TEST TOOL 1: HELLO (Greeting Tool)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/hello?name=Khadija"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/hello?name=Khadija"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "3️⃣  TEST TOOL 2: ADD (Addition Calculator)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/add?a=25&b=75"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/add?a=25&b=75"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "4️⃣  TEST TOOL 3: MULTIPLY (Multiplication)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/multiply?a=12&b=8"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/multiply?a=12&b=8"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "5️⃣  TEST TOOL 4: TEMP-CONVERT (Temperature Converter)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/temp-convert?celsius=25"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/temp-convert?celsius=25"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "6️⃣  TEST TOOL 5: ANALYZE-TEXT (Text Analyzer)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/analyze-text?text=Hello%20World%20123"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/analyze-text?text=Hello%20World%20123"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "7️⃣  TEST TOOL 6: SQRT (Square Root Calculator)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Command:"
echo '  curl "http://localhost:8000/tools/sqrt?number=144"'
echo ""
echo "Response:"
curl -s "http://localhost:8000/tools/sqrt?number=144"
echo ""
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    ✅ ALL TESTS COMPLETE!                      ║"
echo "╔════════════════════════════════════════════════════════════════╗"
echo ""
echo "🌐 View in Browser:"
echo "   • API Docs:  http://localhost:8000/docs"
echo "   • ReDoc:     http://localhost:8000/redoc"
echo ""
echo "📋 Use Test Scripts:"
echo "   • Quick test:         ./quick_test_commands.sh"
echo "   • Comprehensive test: ./comprehensive_test.sh"
echo "   • Simple test:        ./test_endpoints.sh"
echo ""

